M48
; DRILL file {KiCad (6.0.8)} date Tue Jul 25 16:12:30 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-25T16:12:30-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X102.995Y-124.7
T2
X92.0Y-82.1
X92.0Y-122.8
X202.0Y-82.2
X202.0Y-122.8
T0
M30
